add yannicks deployment config repo
baloise-incubator/okd4-apps-root-config pull request #5
Opened 2020-12-21 16:33 UTC by yannickholzenkamp

Am I doing this right, @niiku ? 😅

2020-12-21 16:37 UTC, christiansiegel requested changes
almost :wink:

2020-12-21 16:37 UTC, christiansiegel commented on apps/okd4-yannickholzenkamp-apps.yaml
> +applications:
```suggestion
applications: {}
```

2020-12-21 16:37 UTC, christiansiegel commented on bootstrap/values.yaml
> + - name: okd4-yannickholzenkamp-apps.yaml
```suggestion
 - name: okd4-yannickholzenkamp-apps
```

2020-12-21 16:39 UTC, christiansiegel approved these changes
lgtm

2020-12-21 16:39 UTC, yannickholzenkamp commented
Thanks!

2020-12-21 17:11 UTC, yannickholzenkamp commented
Also added two applications in my apps.yaml. @christiansiegel, could you merge it if it's ok? I don't have the permissions to do that 🙂

2020-12-21 17:17 UTC, christiansiegel commented
You can also add those two webhooks (both with json content type) to your config repo for the future:
- https://tekton-syncapps-route-tekton-chatopshandler.apps.okd.baloise.dev/
- https://argocd.baloise.dev/api/webhook

The first will sync the applications (creates one application entry in the yaml here for every folder in your repo). The second triggers ArgoCD to sync the config to the cluster.

2020-12-21 17:18 UTC, merged

2020-12-21 17:20 UTC, yannickholzenkamp commented
Will do that - thanks!

2020-12-21 17:37 UTC, yannickholzenkamp commented
@christiansiegel do you have an idea what i missed when my apps are still not showing up in argocd?

2020-12-21 17:53 UTC, christiansiegel commented
> @christiansiegel do you have an idea what i missed when my apps are still not showing up in argocd?

Looks like ArgoCD is stuck trying to sync the cluster infra apps since last night. @niiku could you please have a look at this?

2020-12-22 02:14 UTC, niiku commented
The OKDv4 update went a bit south but all should be working again. DockerHub has now pull limits...

2020-12-22 09:41 UTC, yannickholzenkamp commented
Thanks for fixing, the applications are now visible in ArgoCD. Somehow the resources are missing / the images are not deployed. Do you maybe have a hint for me what's wrong w/ my configuration?

2020-12-22 11:59 UTC, niiku commented
@yannickholzenkamp Rename Charts.yaml to Chart.yaml so ArgoCD recognizes it as Helm Chart

2020-12-22 12:26 UTC, yannickholzenkamp commented
Ok, stupid me 🤦 Thanks a lot!